name: Patater
description: Patater is my outlet for my free and open works.
url: "https://patater.com"
baseurl: ""

liquid:
  error_mode: strict

markdown: kramdown
highlighter: pygments
encoding: utf-8
permalink: pretty
relative_permalinks: false
plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README

defaults:
  -
    scope:
      path: ""
    values:
      author: Jaeden Amero
      language: en
      site_map_priority: 0.5
defaults:
  -
    scope:
      path: ""
    values:
      author: Jaeden Amero
      language: en
      site_map_priority: 0.5
defaults:
  -
    scope:
      path: "images"
    values:
      image: true
