name: Patater
description: Patater is my outlet for my free and open works.
markdown: kramdown
highlighter: pygments
encoding: utf-8
permalink: pretty
relative_permalinks: false
safe: true

defaults:
  -
    scope:
      path: ""
    values:
      author: Jaeden Amero
      language: en
      site_map_priority: 0.5
defaults:
  -
    scope:
      path: ""
    values:
      author: Jaeden Amero
      language: en
      site_map_priority: 0.5
