name: Patater
markdown: redcarpet
pygments: true
encoding: utf-8
permalink: pretty
relative_permalinks: false

defaults:
  -
    scope:
      path: ""
    values:
      author: Jaeden Amero
      language: en
      site_map_priority: 0.5
